from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from ecologica import views
from rest_framework.urlpatterns import format_suffix_patterns
from views import ExcelExport1

urlpatterns = patterns('',

    url(r'^$', views.ingresar, name='ingresar'),
	url(r'^logout$', views.logout_view, name="logout"),
	url(r'^Dashboard/$',views.main,name = "index"),
	url(r'^password_change/$',views.password_change, name='password_change'),
	
#Vistas
	url(r'^expedientes/$', views.expedientes, name='expedientes'),
	url(r'^expedientesEnVigor/$', views.expedientesVigor, name='expedientesVigor'),
	url(r'^riesgos/$', views.riesgos, name='riesgos'),
	url(r'^expedientes/(?P<id_Expediente>\d+)/$',views.ExpedienteView, name='expediente'),
	url(r'^expedientes/(?P<id_Expediente>\d+)/generaCertificado/$',views.certificado, name='generaPdf'),
	url(r'^clientes/(?P<id_Cliente>\d+)/NuevoExpediente/$',views.creaExpediente, name='nuevoExpediente'),
	url(r'^clientes/$',views.clientes, name='clientes'),
	url(r'^clientes/(?P<id_Cliente>\d+)/$',views.clienteView, name='cliente'),
	url(r'^clientes/NuevoCliente/$',views.creaCliente, name='nuevoCliente'),
	url(r'^clientes/(?P<id_Cliente>\d+)/NuevaFactura/$',views.creaFactura, name='nuevaFactura'),
	url(r'^inspectores/$',views.inspectores, name='inspectores'),
	url(r'^inspectores/NuevoInspector/$',views.creaInspector, name='nuevoInspector'),
	url(r'^parcelas/(?P<id_Parcela>\d+)/$',views.parcelaView, name='parcela'),
	url(r'^parcelasGanaderia/(?P<id_Parcela>\d+)/$',views.parcelaGanadoView, name='parcelaGanado'),
	url(r'^productoIndustrial/(?P<id_Parcela>\d+)/$',views.productoIndustrialView, name='productoIndustrial'),
	url(r'^excelfile1.xlsx/?',ExcelExport1.as_view(),name='excelfile1'),
	url(r'^expedientesEnVigor/(?P<tipo>\d+)/$',views.ExpedientesVigorArchivo,name='expVigor'),
	url(r'^Facturacion/?',views.Factura,name='factura'),
	url(r'^excelfile2/(?P<year1>\d{4})/(?P<month1>\d{2})/(?P<day1>\d+)/(?P<year2>\d{4})/(?P<month2>\d{2})/(?P<day2>\d+)/(?P<factu>\d+)/$',views.ExcelExport2,name='excelfile2'),
	url(r'^datosPagos/$',views.datosPagos,name='datosPagos'),
	url(r'^expedientesCertificados/$', views.expedientesCertificados, name='expedientesCertificados'),
	url(r'^visitasPlanificadas/$', views.VisitaPlanificada, name='visitasPlanificadas'),
	url(r'^Auditorias/$', views.AuditoriasRealizadas, name='auditoriasRealizadas'),
	url(r'^Auditorias/(?P<id_Informe>\d+)/generaInforme/$',views.informeVisita, name='generaIV'),
	url(r'^planificaciones/(?P<year1>\d{4})/(?P<month1>\d{2})/(?P<day1>\d+)/(?P<year2>\d{4})/(?P<month2>\d{2})/(?P<day2>\d+)$', views.generaPlanificaciones, name='generaPlanificaciones'),
	url(r'^actuaciones/(?P<year1>\d{4})/(?P<month1>\d{2})/(?P<day1>\d+)/(?P<year2>\d{4})/(?P<month2>\d{2})/(?P<day2>\d+)/$', views.generaActuaciones, name='generaActuaciones'),
	url(r'^incumplimientos/(?P<year1>\d{4})/(?P<month1>\d{2})/(?P<day1>\d+)/(?P<year2>\d{4})/(?P<month2>\d{2})/(?P<day2>\d+)$', views.generaIncumplimientos, name='generaIncumplimientos'),
	
	
#API
	url(r'^api/perfil/$', views.PerfilList.as_view()),
    url(r'^api/perfil/(?P<pk>[0-9]+)/$', views.PerfilDetail.as_view()),
	url(r'^api/usuarios/$', views.UsuariosList.as_view()),
    url(r'^api/usuarios/(?P<pk>[0-9]+)/$', views.UsuariosDetail.as_view()),
	url(r'^api/provincias/$', views.ProvinciaList.as_view()),
    url(r'^api/provincias/(?P<pk>[0-9]+)/$', views.ProvinciaDetail.as_view()),
	url(r'^api/municipios/$', views.MunicipioList.as_view()),
    url(r'^api/municipios/(?P<pk>[0-9]+)/$', views.MunicipioDetail.as_view()),
	url(r'^api/expedientes/$', views.ExpedienteList.as_view()),
    url(r'^api/expedientes/(?P<pk>[0-9]+)/$', views.ExpedienteDetail.as_view()),
	url(r'^api/interlocutor/$', views.InterlocutoresList.as_view()),
    url(r'^api/interlocutor/(?P<pk>[0-9]+)/$', views.InterlocutoresDetail.as_view()),
	url(r'^api/clientes/$', views.ClienteList.as_view()),
    url(r'^api/clientes/(?P<pk>[0-9]+)/$', views.ClienteDetail.as_view()),
	url(r'^api/contacto/$', views.ContactoList.as_view()),
    url(r'^api/contacto/(?P<pk>[0-9]+)/$', views.ContactoDetail.as_view()),
	url(r'^api/formajuridica/$', views.FormaJuridicaList.as_view()),
    url(r'^api/formajuridica/(?P<pk>[0-9]+)/$', views.FormaJuridicaDetail.as_view()),
	url(r'^api/ProductoAgricola/$', views.ProductoAgricolaList.as_view()),
    url(r'^api/ProductoAgricola/(?P<pk>[0-9]+)/$', views.ProductoAgricolaDetail.as_view()),
	url(r'^api/ProductoGanaderia/$', views.ProductoGanaderiaList.as_view()),
    url(r'^api/ProductoGanaderia/(?P<pk>[0-9]+)/$', views.ProductoGanaderiaDetail.as_view()),
	url(r'^api/ProductoIndustria/$', views.ProductoIndustriaList.as_view()),
    url(r'^api/ProductoIndustria/(?P<pk>[0-9]+)/$', views.ProductoIndustriaDetail.as_view()),
	url(r'^api/Variedades/$', views.VariedadesList.as_view()),
    url(r'^api/Variedades/(?P<pk>[0-9]+)/$', views.VariedadesDetail.as_view()),
	url(r'^api/VisitaParcela/$', views.VisitaParcelaList.as_view()),
    url(r'^api/VisitaParcela/(?P<pk>[0-9]+)/$', views.VisitaParcelaDetail.as_view()),
	url(r'^api/Auditoria/$', views.AuditoriaList.as_view()),
    url(r'^api/Auditoria/(?P<pk>[0-9]+)/$', views.AuditoriaDetail.as_view()),
	url(r'^api/Incumplimiento/$', views.IncumplimientoList.as_view()),
    url(r'^api/Incumplimiento/(?P<pk>[0-9]+)/$', views.IncumplimientoDetail.as_view()),
	url(r'^api/AccionesCorrectivas/$', views.AccionesCorrectivasList.as_view()),
    url(r'^api/AccionesCorrectivas/(?P<pk>[0-9]+)/$', views.AccionesCorrectivasDetail.as_view()),
	url(r'^api/Evaluacion/$', views.EvaluacionList.as_view()),
    url(r'^api/Evaluacion/(?P<pk>[0-9]+)/$', views.EvaluacionDetail.as_view()),
	url(r'^api/Parcela/$', views.ParcelaList.as_view()),
    url(r'^api/Parcela/(?P<pk>[0-9]+)/$', views.ParcelaDetail.as_view()),
	url(r'^api/historicoCultivos/$', views.HistoricoCultivosList.as_view()),
    url(r'^api/historicoCultivos/(?P<pk>[0-9]+)/$', views.HistoricoCultivosDetail.as_view()),
	url(r'^api/Inspector/$', views.InspectorList.as_view()),
    url(r'^api/Inspector/(?P<pk>[0-9]+)/$', views.InspectorDetail.as_view()),
	url(r'^api/UsuarioInspector/$', views.UsuarioInspectorList.as_view()),
    url(r'^api/UsuarioInspector/(?P<pk>[0-9]+)/$', views.UsuarioInspectorDetail.as_view()),
	url(r'^api/imagenes/$', views.ImagenesList.as_view()),
    url(r'^api/imagenes/(?P<pk>[0-9]+)/$', views.ImagenesDetail.as_view()),
    url(r'^api/RecolectorParcelas/$', views.RecolectorParcelasList.as_view()),
    url(r'^api/RecolectorParcelas/(?P<pk>[0-9]+)/$', views.RecolectorParcelasDetail.as_view()),
	url(r'^api/RecolectorErrores/$', views.RecolectorErroresList.as_view()),
    url(r'^api/RecolectorErrores/(?P<pk>[0-9]+)/$', views.RecolectorErroresDetail.as_view()),
    url(r'^api/Riesgos/$', views.RiesgoList.as_view()),
    url(r'^api/Riesgos/(?P<pk>[0-9]+)/$', views.RiesgoDetail.as_view()),
	url(r'^api/Ganado/$', views.GanadoList.as_view()),
    url(r'^api/Ganado/(?P<pk>[0-9]+)/$', views.GanadoDetail.as_view()),
	url(r'^api/Facturacion/$', views.FacturacionList.as_view()),
    url(r'^api/Facturacion/(?P<pk>[0-9]+)/$', views.FacturacionDetail.as_view()),
	url(r'^api/nuevosExpedientes/$', views.NuevosExpedientesList.as_view()),
    url(r'^api/nuevosExpedientes/(?P<pk>[0-9]+)/$', views.NuevosExpedientesDetail.as_view()),
	url(r'^api/Industria/$', views.IndustriaList.as_view()),
    url(r'^api/Industria/(?P<pk>[0-9]+)/$', views.IndustriaDetail.as_view()),
	url(r'^api/historicoCertificados/$', views.Historico_CertificadosList.as_view()),
    url(r'^api/historicoCertificados/(?P<pk>[0-9]+)/$', views.Historico_CertificadosDetail.as_view()),
	url(r'^api/parcelasVisita/$', views.parcelas_visitaList.as_view()),
    url(r'^api/parcelasVisita/(?P<pk>[0-9]+)/$', views.parcelas_visitaDetail.as_view()),
	url(r'^api/ganadoVisita/$', views.ganado_visitaList.as_view()),
    url(r'^api/ganadoVisita/(?P<pk>[0-9]+)/$', views.ganado_visitaDetail.as_view()),
	url(r'^api/industriaVisita/$', views.industria_visitaList.as_view()),
    url(r'^api/industriaVisita/(?P<pk>[0-9]+)/$', views.industria_visitaDetail.as_view()),
	url(r'^api/informeVisita/$', views.InformeVisitaList.as_view()),
    url(r'^api/informeVisita/(?P<pk>[0-9]+)/$', views.InformeVisitaDetail.as_view()),
)
urlpatterns = format_suffix_patterns(urlpatterns)